In [1]:
#Reference: https://towardsdatascience.com/converting-yelp-dataset-to-csv-using-pandas-2a4c8f03bd88
import pandas as pd
import json
import numpy as np

In [2]:
################################################
###      MOVIES METADATA
################################################

file_path = './MovieDataset/movies_metadata.csv'
movies_df = pd.read_csv(file_path, usecols=[2,3,5,7,12,14,15,20], parse_dates=True) #usecols=[5,20,7,2,15,14,3,12])#
#print("\nSelected columns:\n")
#print(movies_df.head())

#seperate genres and production_companies
genres = movies_df[['id','genres']]
production_companies = movies_df[['id','production_companies']]
movies_df.drop(['genres','production_companies'], axis=1, inplace=True)

movies_df = pd.DataFrame(movies_df, columns=('id','title','original_language','budget','revenue','release_date'))
movies_df.columns=['movieID','title','language','budget','revenue','releasedate']
print(movies_df.head())

#conversion to int, float and str object
movies_df['movieID']=pd.to_numeric(movies_df['movieID'], errors='coerce')
movies_df['budget']=pd.to_numeric(movies_df['budget'], errors='coerce')
movies_df['revenue']=pd.to_numeric(movies_df['revenue'], errors='coerce')
movies_df['releasedate']=pd.to_datetime(movies_df['releasedate'], format='%Y-%m-%d', errors='coerce')
movies_df.dropna(inplace=True)

#movies_df['movieID'] = movies_df['movieID'].replace(np.nan, 0).astype(np.int64)
movies_df['movieID'] = movies_df['movieID'].astype(int)
movies_df['budget'] = movies_df['budget'].astype(float)
movies_df['revenue'] = movies_df['revenue'].astype(float)


print('\nafter conversion\n')
for column, t in zip(movies_df.columns, movies_df.dtypes):
    if(t == "object"):
        max_len = max(movies_df[column].str.len())
    else:
        max_len = max(movies_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(movies_df.head())



#prepare genres table
d = []
for movieid, genre in zip(genres['id'], genres['genres']):    
    #print(movieid, genre)
    res = list(eval(genre))     
    for x in res: 
        genreid = x['id']
        g = x["name"]
        #print(g)  
        d.append((genreid, movieid, g))
genres_df = pd.DataFrame(d, columns=('genreID', 'movieID', 'genre'))
print(genres_df.head(10))


#conversion to int, float and str object
genres_df['movieID']=pd.to_numeric(genres_df['movieID'], errors='coerce')
genres_df['genreID']=pd.to_numeric(genres_df['genreID'], errors='coerce')

genres_df.dropna(inplace=True)

genres_df['movieID'] = genres_df['movieID'].astype(int)
genres_df['genreID'] = genres_df['genreID'].astype(int)

print('\nafter conversion\n')
for column, t in zip(genres_df.columns, genres_df.dtypes):
    if(t == "object"):
        max_len = max(genres_df[column].str.len())
    else:
        max_len = max(genres_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(genres_df.head())

#prepare production_companies table
d = []
#count = 0
for movieid, company in zip(production_companies['id'], production_companies['production_companies']):    
    #print(count,movieid, company)
    #count+=1
    #if(not pd.isnull(company)):
    try:
        res = list(eval(company))   
        for x in res:    
            pcid = x['id']
            g = x["name"]
            #print(g) 
            d.append((pcid, movieid, g))
    except:
        #print("some error")
        continue

production_companies_df = pd.DataFrame(d, columns=('companyID','movieID', 'companyname'))
print(production_companies_df.head(10))

#conversion to int, float and str object
production_companies_df['movieID']=pd.to_numeric(production_companies_df['movieID'], errors='coerce')
production_companies_df['companyID']=pd.to_numeric(production_companies_df['companyID'], errors='coerce')

production_companies_df.dropna(inplace=True)

production_companies_df['movieID'] = production_companies_df['movieID'].astype(int)
production_companies_df['companyID'] = production_companies_df['companyID'].astype(int)



print('\nafter conversion\n')
for column, t in zip(production_companies_df.columns, production_companies_df.dtypes):
    if(t == "object"):
        max_len = max(production_companies_df[column].str.len())
    else:
        max_len = max(production_companies_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(production_companies_df.head())

#save dataframes as csv files
movies_df.to_csv('./MovieDataset/movies_df.csv', index=False)
genres_df.to_csv('./MovieDataset/genres_df.csv', index=False)
production_companies_df.to_csv('./MovieDataset/production_companies_df.csv', index=False)

  movieID                        title language    budget      revenue  \
0     862                    Toy Story       en  30000000  373554033.0
1    8844                      Jumanji       en  65000000  262797249.0
2   15602             Grumpier Old Men       en         0          0.0
3   31357            Waiting to Exhale       en  16000000   81452156.0
4   11862  Father of the Bride Part II       en         0   76578911.0

  releasedate
0  1995-10-30
1  1995-12-15
2  1995-12-22
3  1995-12-22
4  1995-02-10

after conversion

movieID 	 int64 	 469172
title 	 object 	 105
language 	 object 	 2
budget 	 float64 	 380000000.0
revenue 	 float64 	 2787965087.0
releasedate 	 datetime64[ns] 	 2020-12-16 00:00:00

   movieID                        title language      budget      revenue  \
0      862                    Toy Story       en  30000000.0  373554033.0
1     8844                      Jumanji       en  65000000.0  262797249.0
2    15602             Grumpier Old Men       en         0.0          0.0
3    31357            Waiting to Exhale       en  16000000.0   81452156.0
4    11862  Father of the Bride Part II       en         0.0   76578911.0

  releasedate
0  1995-10-30
1  1995-12-15
2  1995-12-22
3  1995-12-22
4  1995-02-10
   genreID movieID      genre
0       16     862  Animation
1       35     862     Comedy
2    10751     862     Family
3       12    8844  Adventure
4       14    8844    Fantasy
5    10751    8844     Family
6    10749   15602    Romance
7       35   15602     Comedy
8       35   31357     Comedy
9       18   31357      Drama

after conversion

genreID 	 int64 	 10770
movieID 	 int64 	 469172
genre 	 object 	 15

   genreID  movieID      genre
0       16      862  Animation
1       35      862     Comedy
2    10751      862     Family
3       12     8844  Adventure
4       14     8844    Fantasy
   companyID movieID                             companyname
0          3     862                 Pixar Animation Studios
1        559    8844                        TriStar Pictures
2       2550    8844                            Teitler Film
3      10201    8844               Interscope Communications
4       6194   15602                            Warner Bros.
5      19464   15602                          Lancaster Gate
6        306   31357  Twentieth Century Fox Film Corporation
7       5842   11862                   Sandollar Productions
8       9195   11862                     Touchstone Pictures
9        508     949                     Regency Enterprises

after conversion

companyID 	 int64 	 96067
movieID 	 int64 	 469172
companyname 	 object 	 101

   companyID  movieID                companyname
0          3      862    Pixar Animation Studios
1        559     8844           TriStar Pictures
2       2550     8844               Teitler Film
3      10201     8844  Interscope Communications
4       6194    15602               Warner Bros.

In [3]:
################################################
###      CREDITS
################################################

file_path1 = './MovieDataset/credits.csv'
credits_df = pd.read_csv(file_path1)#, usecols=[0,2,3,5,7,12,14,15,20]) #usecols=[5,20,0,7,2,15,14,3,12])#
print(credits_df.head())

#seperate cast and crew
cast_credits = credits_df[['id', 'cast']]
crew_credits = credits_df[['id', 'crew']]


#prepare cast table
d = []
for movieid, cast in zip(cast_credits['id'], cast_credits['cast']):    
    #print(movieid, cast)
    res = list(eval(cast))     
    for x in res:       
        cast_id = x['cast_id']
        name = x["name"]
        character = x['character']
        gender = x['gender']  
        d.append((cast_id, movieid, name, character, gender))
    #break
cast_credits_df = pd.DataFrame(d, columns=('castID', 'movieID', 'name', 'character','gender'))
print(cast_credits_df.head(10))


#conversion to int, float and str object
cast_credits_df['movieID']=pd.to_numeric(cast_credits_df['movieID'], errors='coerce')
cast_credits_df['castID']=pd.to_numeric(cast_credits_df['castID'], errors='coerce')
cast_credits_df['gender']=pd.to_numeric(cast_credits_df['gender'], errors='coerce')

cast_credits_df.dropna(inplace=True)

cast_credits_df['movieID'] = cast_credits_df['movieID'].astype(int)
cast_credits_df['castID'] = cast_credits_df['castID'].astype(int)
cast_credits_df['gender'] = cast_credits_df['gender'].astype(int)



print('\nafter conversion\n')
for column, t in zip(cast_credits_df.columns, cast_credits_df.dtypes):
    if(t == "object"):
        max_len = max(cast_credits_df[column].str.len())
    else:
        max_len = max(cast_credits_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(cast_credits_df.head())


#prepare crew table
d = []
for movieid, crew in zip(crew_credits['id'], crew_credits['crew']):    
    #print(movieid, crew)
    res = list(eval(crew))     
    for x in res:    
        crew_id =x['id']
        name = x["name"]
        department = x['department']
        gender = x['gender']  
        job = x['job']
        d.append((crew_id, movieid, name, department, job, gender))
    #break
crew_credits_df = pd.DataFrame(d, columns=('crewID', 'movieID','name','department','job','gender'))
print(crew_credits_df.head(10))

#conversion to int, float and str object
crew_credits_df['movieID']=pd.to_numeric(crew_credits_df['movieID'], errors='coerce')
crew_credits_df['crewID']=pd.to_numeric(crew_credits_df['crewID'], errors='coerce')
crew_credits_df['gender']=pd.to_numeric(crew_credits_df['gender'], errors='coerce')

crew_credits_df.dropna(inplace=True)

crew_credits_df['movieID'] = crew_credits_df['movieID'].astype(int)
crew_credits_df['crewID'] = crew_credits_df['crewID'].astype(int)
crew_credits_df['gender'] = crew_credits_df['gender'].astype(int)



print('\nafter conversion\n')
for column, t in zip(crew_credits_df.columns, crew_credits_df.dtypes):
    if(t == "object"):
        max_len = max(crew_credits_df[column].str.len())
    else:
        max_len = max(crew_credits_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(crew_credits_df.head())

#save dataframes as csv files
cast_credits_df.to_csv('./MovieDataset/cast_credits_df.csv', index=False)
crew_credits_df.to_csv('./MovieDataset/crew_credits_df.csv', index=False)

                                                cast  \
0  [{'cast_id': 14, 'character': 'Woody (voice)',...
1  [{'cast_id': 1, 'character': 'Alan Parrish', '...
2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...
3  [{'cast_id': 1, 'character': "Savannah 'Vannah...
4  [{'cast_id': 1, 'character': 'George Banks', '...

                                                crew     id
0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...    862
1  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...   8844
2  [{'credit_id': '52fe466a9251416c75077a89', 'de...  15602
3  [{'credit_id': '52fe44779251416c91011acb', 'de...  31357
4  [{'credit_id': '52fe44959251416c75039ed7', 'de...  11862
   castID  movieID               name                character  gender
0      14      862          Tom Hanks            Woody (voice)       2
1      15      862          Tim Allen   Buzz Lightyear (voice)       2
2      16      862        Don Rickles  Mr. Potato Head (voice)       2
3      17      862         Jim Varney       Slinky Dog (voice)       2
4      18      862      Wallace Shawn              Rex (voice)       2
5      19      862  John Ratzenberger             Hamm (voice)       2
6      20      862        Annie Potts          Bo Peep (voice)       1
7      26      862        John Morris             Andy (voice)       0
8      22      862    Erik von Detten              Sid (voice)       2
9      23      862     Laurie Metcalf       Mrs. Davis (voice)       1

after conversion

castID 	 int64 	 1119
movieID 	 int64 	 469172
name 	 object 	 47
character 	 object 	 390
gender 	 int64 	 2

   castID  movieID           name                character  gender
0      14      862      Tom Hanks            Woody (voice)       2
1      15      862      Tim Allen   Buzz Lightyear (voice)       2
2      16      862    Don Rickles  Mr. Potato Head (voice)       2
3      17      862     Jim Varney       Slinky Dog (voice)       2
4      18      862  Wallace Shawn              Rex (voice)       2
   crewID  movieID              name  department                 job  gender
0    7879      862     John Lasseter   Directing            Director       2
1   12891      862       Joss Whedon     Writing          Screenplay       2
2       7      862    Andrew Stanton     Writing          Screenplay       2
3   12892      862        Joel Cohen     Writing          Screenplay       2
4   12893      862      Alec Sokolow     Writing          Screenplay       0
5   12894      862     Bonnie Arnold  Production            Producer       1
6   12895      862        Ed Catmull  Production  Executive Producer       0
7   12896      862  Ralph Guggenheim  Production            Producer       2
8   12897      862        Steve Jobs  Production  Executive Producer       2
9       8      862       Lee Unkrich     Editing              Editor       2

after conversion

crewID 	 int64 	 1908001
movieID 	 int64 	 469172
name 	 object 	 44
department 	 object 	 17
job 	 object 	 56
gender 	 int64 	 2

   crewID  movieID            name department         job  gender
0    7879      862   John Lasseter  Directing    Director       2
1   12891      862     Joss Whedon    Writing  Screenplay       2
2       7      862  Andrew Stanton    Writing  Screenplay       2
3   12892      862      Joel Cohen    Writing  Screenplay       2
4   12893      862    Alec Sokolow    Writing  Screenplay       0

In [4]:
################################################
###      KEYWORDS
################################################

file_path2 = './MovieDataset/keywords.csv'
keywords = pd.read_csv(file_path2)#, usecols=[0,2,3,5,7,12,14,15,20]) #usecols=[5,20,0,7,2,15,14,3,12])#
print(keywords.head())

#prepare keywords table
d = []
for movieid, keywords in zip(keywords['id'], keywords['keywords']):    
    #print(movieid, keywords)
    res = list(eval(keywords))     
    for x in res:  
        keyid = x['id']
        name = x["name"]
        d.append((keyid,movieid, name))
    #break
keywords_df = pd.DataFrame(d, columns=('keyID','movieID', 'keyword'))
print(keywords_df.head(10))

#conversion to int, float and str object
keywords_df['movieID']=pd.to_numeric(keywords_df['movieID'], errors='coerce')
keywords_df['keyID']=pd.to_numeric(keywords_df['keyID'], errors='coerce')


keywords_df.dropna(inplace=True)

keywords_df['movieID'] = keywords_df['movieID'].astype(int)
keywords_df['keyID'] = keywords_df['keyID'].astype(int)




print('\nafter conversion\n')
for column, t in zip(keywords_df.columns, keywords_df.dtypes):
    if(t == "object"):
        max_len = max(keywords_df[column].str.len())
    else:
        max_len = max(keywords_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(keywords_df.head())

#save dataframes as csv files
keywords_df.to_csv('./MovieDataset/keywords_df.csv', index=False)

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
    keyID  movieID            keyword
0     931      862           jealousy
1    4290      862                toy
2    5202      862                boy
3    6054      862         friendship
4    9713      862            friends
5    9823      862            rivalry
6  165503      862      boy next door
7  170722      862            new toy
8  187065      862  toy comes to life
9   10090     8844         board game

after conversion

keyID 	 int64 	 238884
movieID 	 int64 	 468707
keyword 	 object 	 48

   keyID  movieID     keyword
0    931      862    jealousy
1   4290      862         toy
2   5202      862         boy
3   6054      862  friendship
4   9713      862     friends

In [5]:
################################################
###      RATINGS
################################################

file_path3 = './MovieDataset/ratings.csv'
ratings_df = pd.read_csv(file_path3, usecols=[0,1,2])#, usecols=[0,2,3,5,7,12,14,15,20]) #usecols=[5,20,0,7,2,15,14,3,12])#

ratings_df.columns=['userID','movieID','rating']
print(ratings_df.head())


#conversion
ratings_df['movieID']=pd.to_numeric(ratings_df['movieID'], errors='coerce')
ratings_df['userID']=pd.to_numeric(ratings_df['userID'], errors='coerce')
ratings_df['rating']=pd.to_numeric(ratings_df['rating'], errors='coerce')
ratings_df.dropna(inplace=True)

ratings_df['movieID'] = ratings_df['movieID'].astype(int)
ratings_df['userID'] = ratings_df['userID'].astype(int)
ratings_df['rating'] = ratings_df['rating'].astype(float)


print('\nafter conversion\n')
for column, t in zip(ratings_df.columns, ratings_df.dtypes):
    if(t == "object"):
        max_len = max(ratings_df[column].str.len())
    else:
        max_len = max(ratings_df[column])
    print(column,'\t', t, '\t', max_len)
    
print()
print(ratings_df.head())

#save dataframes as csv files
ratings_df.to_csv('./MovieDataset/ratings_df.csv', index=False)

   userID  movieID  rating
0       1      110     1.0
1       1      147     4.5
2       1      858     5.0
3       1     1221     5.0
4       1     1246     5.0

after conversion

userID 	 int64 	 270896
movieID 	 int64 	 176275
rating 	 float64 	 5.0

   userID  movieID  rating
0       1      110     1.0
1       1      147     4.5
2       1      858     5.0
3       1     1221     5.0
4       1     1246     5.0

In [6]:
#Unable to parse string "1997-08-20" at position 19730
#Unable to parse string "2012-09-29" at position 29501
#Unable to parse string "2012-09-29" at position 29502
#movies_df.drop(movies_df[movies_df.movieID=="1997-08-20"].index, inplace=True)
#movies_df.drop(index=[19730,29501,29502], inplace=True)
#movies_df['movieID'] = movies_df['movieID'].replace(np.nan, 0).astype(np.int64)